#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Feb 08 16:24:43 CET 2024
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim ex2_tb_behav -key {Behavioral:sim_1:Functional:ex2_tb} -tclbatch ex2_tb.tcl -view /home/sbo/SSDS/Exams/2023-04-13/ex2_FSM/ex2_tb_behav.wcfg -log simulate.log"
xsim ex2_tb_behav -key {Behavioral:sim_1:Functional:ex2_tb} -tclbatch ex2_tb.tcl -view /home/sbo/SSDS/Exams/2023-04-13/ex2_FSM/ex2_tb_behav.wcfg -log simulate.log

