#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Jan 20 15:52:53 CET 2024
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim RAM_eraser_tb_behav -key {Behavioral:sim_1:Functional:RAM_eraser_tb} -tclbatch RAM_eraser_tb.tcl -view /home/sbo/SSDS/Exams/2022-02-11/ex3_HLSM_RAM_eraser/RAM_eraser_tb_behav.wcfg -log simulate.log"
xsim RAM_eraser_tb_behav -key {Behavioral:sim_1:Functional:RAM_eraser_tb} -tclbatch RAM_eraser_tb.tcl -view /home/sbo/SSDS/Exams/2022-02-11/ex3_HLSM_RAM_eraser/RAM_eraser_tb_behav.wcfg -log simulate.log

